### PR TITLE
MarkovNetwork: Optimizing activate_network

### PR DESCRIPTION
**Pull request by joaoavf**
## What does this PR do?
This PR optimizes the `activate_network` method. It makes my simulations run slightly faster than 4x the original speed.

I have made a Cython version for it that runs 14x faster than the original Python code. If you have interest on it, just let me know and I'll send it to you as well.

## Where should the reviewer start?
Reading the `activate_network` method and making tests.

## How should this PR be tested?
I tested it checking if output and states were the same as the original version. Important to note that there is a random number generator inside `activate_network`, so you should set the seed before tests.

## Any background context you want to provide?
I was asked to optimize this on a freelance platform, and the person who hired me was kind enough to let me make the pull request.

## What are the relevant issues?
None

## Screenshots (if appropriate)
None

## Questions:

- Do the docs need to be updated? No
- Does this PR add new (Python) dependencies? No

### CODE REVIEW

**Comment by rhiever** [comment]
Interesting - thank you for the PR and suggestion. Also interesting to hear that someone was paying to speed up this code. 👍 

Was the primary speedup in the non-Cython version of this code from changing this original line

```Python
mg_input_index = int(''.join([str(int(val)) for val in mg_input_values]), base=2)
```

to this?

```Python
for i in range(len_arr):
    if self.states[mg_input_ids[len_arr - i - 1]]:
        tmp = mg_input_index + marker
        mg_input_index = tmp
    tmp2 = marker * 2
    marker = tmp2
```

Is the rest of the loop re-designs in this PR solely for Cython speedups?

**Comment by joaoavf** [comment]
Hello Randy,

The Cython speed-up comes from these improvements:

1. `np.random.uniform()` is slow, I used a wrapped C function for it
2. `np.binary_repr()` is slow, I used Python built in `bin()` for it
3. Creating a loop to set the `np.array` directly instead of using `np.bitwise_or()` (this was the biggest improvement if I recall correctly)
4. Changing `int(''.join([str(int(val)) for val in mg_input_values]), base=2)` to a loop
5. Changing `np.where(markov_gate[mg_input_index, :] >= roll)[0][0]` to a loop inside a subarray
6. Some other slight improvements that sum up.

I might be leaving something behind, but I think those were the most important ones.

The code reads a bit weird because it was optimized for Cython, if you want I can write a more Pythonic version of it.

**Comment by rhiever** [comment]
>The code reads a bit weird because it was optimized for Cython, if you want I can write a more Pythonic version of it.

👍, I'd be happy to review a Pythonic port of this code. I don't have plans to add Cython support for this project at the moment, though it's not out of the question if someone wants to champion the issue.

Overall, I'm surprised to hear that the NumPy functions are so relatively slow.

**Comment by joaoavf** [comment]
I was also surprised that `np.random.uniform()` and `np.binary_repr()` were slow. As for the `np.bitwise_or()` it ends up doing a lot of excessive computation when comparing to only changing what will be in fact modified. It is quite tricky to catch those optimizations opportunities with `numpy`, and I had quite a bit of work to be able to do it.

I've updated this PR with a more Pythonic version, it is still about 4x faster than the original Python code and it is passing the output and state tests. Let me know if you need anything else (including the Cython version for the code).

**Comment by rhiever** [comment]
This review required me to dig back into this code - it has been several years since I worked on the internals of MNs. :-)

I've confirmed your findings that switching from NumPy functions to Pythonic loops seems to confer a speedup for the activate function, which will speed up the MNs significantly because that is the most-called function.

I noticed that as I increased the number of inputs/outputs, the speedup eventually went away. I suspect the speedup is realized because NumPy is optimized to work on large arrays of numbers, whereas MNs rarely tend to use large arrays of numbers, e.g., the maximum number of inputs and outputs is typically limited to 4 so the MG array is 2^4 x 2^4 at the largest. Thus, the NumPy overhead required to efficiently operate on large arrays of numbers if not offset here because our arrays tend to be small. Interesting finding!

I will merge this PR. Thank you for the contribution.

**Comment by joaoavf** [comment]
Thanks for the update and for reviewing my PR Randy. I am glad to help.

This kind of problem seem to be a natural fit for Cython, as they are not simple matrix multiplications or other vectorized calculations. In my own projects I have been able to achieve very significant speed-ups in similar problems, so I imagine it would still be quite faster with larger arrays. The issue with Cython is that it is a bit of hassle to distribute.

**Comment by rhiever** [comment]
>The issue with Cython is that it is a bit of hassle to distribute.

Exactly - that is why I tend to avoid Cython for my publicly-distributed code. It's not fun dealing with installation issues on GitHub all the time.

Looking back at this code, I actually wonder if similar speedups could be realized with the use of multiprocessing. Each MG activation can be processed separately then the results logical OR'd together. I suspect it wouldn't be worth it for a MN with just a handful of MGs, but once the MGs start numbering in the 100s...

**Comment by joaoavf** [comment]
I wonder if it would have this speedups as well as multiprocessing is a bit expensive to start, so multithreading might be a better option, but I am still not sure on how it might perform. I have never parallelized such a short routine.

Parallelizing `for _ in range(num_activations):` seems easy. It also seems possible to partially parallelize `for markov_gate, mg_input_ids, mg_output_ids in zip(self.markov_gates, self.markov_gate_input_ids, self.markov_gate_output_ids):`, but it doesn't look very trivial.

Anyways, are you looking for a PR on multiprocessing/multithreading? I can explore if it is viable and send you one whenever I have a bit of free time.

**Comment by rhiever** [comment]
Parallelizing the `num_activations` loop is actually the more difficult one because the 2nd activation needs the updated inputs/outputs from the 1st activation, the 3rd from the 2nd and 1st, etc. Thus, there is significant reliance on previous activations, which makes it difficult to parallelize.

If you're open to exploring parallelization of the inner loop `for markov_gate, mg_input_ids, mg_output_ids in zip(self.markov_gates, self.markov_gate_input_ids, self.markov_gate_output_ids):`, I'd be happy to review the work with you in a PR. It could be added as an optional parameter `n_jobs` (default value=1, or no parallelization), similar to scikit-learn. I'm curious to learn whether parallelization will help there.

**Comment by joaoavf** [comment]
Great Randy! Thanks for the comments on the difficulty of parallelizing `num_activations`, it will help me better focus my efforts.

I will work on this on the next few days. I have been quite busy applying for jobs, but once I have a bit more of free time I will test some multiprocessing and multithreading implementations.

**Comment by joaoavf** [comment]
Hello Randy, I have made a few attempts to parallelize the `activate_network` method, but I was unable to see speed-ups.

It seems that it is very expensive to start multiple threads to process a somewhat small batch and I haven't figured out a way to make it work in an efficient manner.

If someone finds a solution on how to parallelize this, I will be very interested to see it.

Those were interesting problems to work on, thanks!

**Comment by rhiever** [comment]
Thank you for looking into this possibility, @joaoavf. Do you have a branch with your parallelization attempts?

**Comment by joaoavf** [comment]
I didn't, I had only made some attempts on a Jupyter Notebook. 

If you want to look at what I did, I just created a branch with a simple copy and paste from what was my last attempt and pushed it into: https://github.com/joaoavf/MarkovNetwork/tree/mp

Note that I changed the signature of `activate_network` to pass all the data at once.

If you find a way into it please let me know!

Best!

**Pull request merged**
